name: ✨ Feature Request
description: Suggest a new feature or enhancement for prconflict
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions or workarounds you've considered...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: How would this feature be used? Provide concrete examples.
      placeholder: |
        # Example 1: New command line flag
        prconflict --format json --output results.json
        
        # Example 2: New configuration option
        prconflict --config .prconflict.yml
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Critical for my workflow
        - Urgent - Blocking my work
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area of prconflict would this feature affect?
      options:
        - CLI interface
        - GitHub API integration
        - Output formatting
        - Configuration
        - Performance
        - Documentation
        - Testing
        - Other (please specify below)
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this? (Select all that apply)
      options:
        - label: New command line option/flag
        - label: New output format
        - label: Performance improvement
        - label: Better error handling
        - label: Configuration enhancement
        - label: Integration with other tools
        - label: Developer experience improvement
        - label: Other

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Do you have any ideas about how this feature could be implemented?
      placeholder: |
        Any technical considerations, potential challenges, or implementation ideas...

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: How would this feature impact existing functionality?
      placeholder: |
        - Would this be a breaking change?
        - Does it affect existing APIs or behavior?
        - What would be the migration path?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I would prefer someone else implements this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Links to similar features in other tools, mockups, related issues, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting this feature request.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I have considered the impact on existing functionality
          required: true
        - label: I have provided concrete usage examples
          required: true 